INSERT INTO mcvalue (name, isComboItem, comboItemNumber, sizeable, type, notComboAble, imageSrc)
VALUES 
('McChicken',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/McChicken.jpg'),
('McDouble',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/McDouble.jpg'),
('4 Nuggets',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/Chicken-McNuggets.jpg'),
('McChkn Bis',
TRUE,
'999',
FALSE,
'Breakfast',
FALSE,
'/images/mcChknBis.jpg'),
('Chkn McGrid',
TRUE,
'999',
FALSE,
'Breakfast',
FALSE,
'/images/chknMcGrid.jpg'),
('Hashbrown',
FALSE,
'999',
FALSE,
'Breakfast',
TRUE,
'/images/hashbrown.jpg'),
('Saus Burrito',
TRUE,
'999',
FALSE,
'Breakfast',
FALSE,
'/images/sausBurrito.jpg'),
('Saus Muffin',
TRUE,
'999',
FALSE,
'Breakfast',
FALSE,
'/images/sausMuffin.jpg'),
('Saus Biscuit',
TRUE,
'999',
FALSE, 
'Breakfast',
FALSE,
'/images/sausBis.jpg'),
('Saus McGrid',
FALSE,
'999',
FALSE,
'Breakfast',
TRUE,
'/images/Sausage-McGriddles.jpg'),
('Fries',
FALSE,
'999',
TRUE, 
'Lunch',
TRUE,
'/images/fries.jpg'),
('20 Nuggets',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/Chicken-McNuggets.jpg');

INSERT INTO salads (name, isComboItem, comboItemNumber, sizeable, type, notComboAble, imageSrc)
VALUES 
('Ranch Salad',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/ranch-salad.jpg'),
('SW Salad',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/southwest-salad.jpg'),
('Side Salad',
FALSE,
'999',
FALSE,
'Lunch',
TRUE,
'/images/side-salad.png');

INSERT INTO happy_meals (name, sizeable, imageSrc)
VALUES 
('HM Hambrg',
FALSE,
'/images/h-mcdonalds-Hamburger.jpg'),
('HM 4 Nuggets',
FALSE,
'/images/h-mcdonalds-Chicken-McNuggets.jpg'),
('HM 6 Nuggets',
FALSE,
'/images/mcdonalds-Chicken-McNuggets-Mighty-Kids-Meals.jpg');

INSERT INTO lsm (name, sizeable, imageSrc)
VALUES 
('Classic Pack Big Mac',
FALSE,
'/images/classic-pack-big-mac.jpg'),
('BTS Meal',
FALSE,
'/images/bts-meal.jpg'),
('Travis-Scott Meal',
FALSE,
'/images/travis-scott-meal.jpg'),
('J Balvin Meal',
FALSE,
'/images/j-balvin-mcdonalds-meal.jpg');

INSERT INTO condiments (name, sizeable, imageSrc)
VALUES 
('BBQ',
FALSE,
'/images/bbq-sauce.jpg'),
('Sweet Sour',
FALSE,
'/images/sweet-sauce.jpg'),
('Hot Must',
FALSE,
'/images/t-hot-mustard-sauce.jpg'),
('Pure Honey',
FALSE,
'/images/pure-honey.jpg'),
('Ranch',
FALSE,
'/images/ranch-sauce.jpg'),
('Buffalo',
FALSE,
'/images/buffalo-sauce.jpg'),
('Honey Must',
FALSE,
'/images/honey-mustard.jpg'),
('Sweet Chili',
FALSE,
'/images/sweet-chili-sauce.jpg'),
('Ketchup',
FALSE,
'/images/ketchup.jpg'),
('Mustard',
FALSE,
'/images/mustard.jpg'),
('Mayo',
FALSE,
'/images/mayo-packet.jpg'),
('Strawberry',
FALSE,
'/images/strawberry-jam.jpg'),
('Hot Picante',
FALSE,
'/images/hot-picante.jpg'),
('Creamer',
FALSE,
'/images/creamer.jpg'),
('Sugar',
FALSE,
'/images/sugar-packet.jpg'),
('Equal',
FALSE,
'/images/equal-packet.jpg'),
('Splenda',
FALSE,
'/images/splenda-packet.jpg');





