INSERT INTO dessert (name, sizeable, imageSrc)
VALUES 
('Apple Pie',
FALSE,
'/images/apple-pie.jpg'),
('Strwbry Pie',
FALSE,
'/images/strawberry-pie.jpg'),
('2 Apple Pies',
FALSE,
'/images/apple-pie.jpg'),
('2 Strwbry Pie',
FALSE,
'/images/strawberry-pie.jpg'),
('Oreo Mcflry',
TRUE,
'/images/oreo-mcflurry-snack.jpg'),
('M&M Mcflry',
TRUE,
'/images/mm-mcflurry-snack.jpg'),
('Cone',
FALSE,
'/images/Cone.jpg'),
('Fudge Sundae',
FALSE,
'/images/Hot-Fudge-Sundae.jpg'),
('Crml Sundae',
FALSE,
'/images/Hot-Caramel-Sundae.jpg'),
('Strwbry Sundae',
FALSE,
'/images/strawberry-sundae.jpg'),
('Plain Sundae',
FALSE,
'/images/plain-sundae.jpg'),
('Cookie',
FALSE,
'/images/cookie.jpg'),
('2 Cookie',
FALSE,
'/images/cookie.jpg'),
('Cookie Box',
FALSE,
'/images/cookie-box.jpg');

INSERT INTO dessert2 (name, sizeable, imageSrc)
VALUES 
('Blubry Mfn',
FALSE,
'/images/blueberry-muffin.jpg'),
('Cinn Roll',
FALSE,
'/images/cinnamon-roll.jpg'),
('Apple Fritter',
FALSE,
'/images/apple-fritter.jpg');