INSERT INTO lunch (name, isComboItem, comboItemNumber, imageSrc)
VALUES 
('Big Mac', 
TRUE,
'1',
'/images/Big-Mac.jpg'
),
('QPC',
TRUE,
'2a',
'/images/QPC.jpg'
),
('Bacon QPC',
TRUE,
'2b',
'/images/qpc-bacon.jpg'
),
('QP Deluxe',
TRUE,
'2c',
'/images/qpc-deluxe.jpg'
),
('Dbl QPC',
TRUE,
'3',
'/images/DQPC.jpg'
),
('Crispy Ckn',
TRUE,
'4a',
'/images/crispy-chicken-sandwich.jpg'),
('Spicy Crispy',
TRUE,
'4b',
'/images/spicy-crispy-chicken-sandwich.jpg'),
('Dlx Crispy',
TRUE,
'4c',
'/images/deluxe-crispy-chicken-sandwich.jpg'),
('Dlx Spicy',
TRUE,
'4d',
'/images/spicy-deluxe-crispy-chicken-sandwich.jpg'),
('10 Nuggets',
TRUE,
'5',
'/images/Chicken-McNuggets.jpg'),
('Filet-o-Fish',
TRUE,
'6',
'/images/Filet-O-Fish.jpg'),
('Chs Burger',
TRUE,
'7',
'/images/Cheeseburger.jpg'),
('McChicken',
FALSE,
'',
'/images/McChicken.jpg'),
('Dbl Cheese',
FALSE,
'',
'/images/Double-Cheeseburger.jpg'),
('Triple Chs',
FALSE,
'',
'/images/triple-cheese.jpg'),
('McDouble',
FALSE,
'',
'/images/McDouble.jpg'),
('Fries',
FALSE,
'',
'/images/fries.jpg');

INSERT INTO lunch2 (name, isComboItem, comboItemNumber, imageSrc)
VALUES 
('4 Nuggets',
FALSE,
'',
'/images/Chicken-McNuggets.jpg'),
('6 Nuggets',
TRUE,
'',
'/images/Chicken-McNuggets.jpg'),
('20 Nuggets',
FALSE,
'',
'/images/Chicken-McNuggets.jpg'),
('40 Nuggets',
FALSE,
'',
'/images/Chicken-McNuggets.jpg'),
('Hamburger',
FALSE,
'',
'/images/Hamburger.jpg'),
('Dbl Hamb',
FALSE,
'',
'/images/double-hamburger.jpg'),
('Dbl Cheese',
FALSE,
'',
'/images/Double-Cheeseburger.jpg'),
('Triple Cheese',
FALSE,
'',
'/images/triple-cheese.jpg'),
('McDouble',
FALSE,
'',
'/images/McDouble.jpg'),
('Fries',
FALSE,
'',
'/images/fries.jpg');