INSERT INTO beverages (name, sizeable, imageSrc) 
VALUES 
('Coke',
TRUE,
'/images/coke.png'),
('Diet Coke',
TRUE,
'/images/dietCoke.jpg'),
('Sprite',
TRUE,
'/images/sprite.jpg'),
('Fanta Orange',
TRUE,
'/images/fantaOrange.jpg'),
('Iced Tea',
TRUE,
'/images/icedTea.jpg'),
('Sweet Tea',
TRUE,
'/images/icedTea.jpg'),
('Coffee',
TRUE,
'/images/coffee.jpg'),
('Decaf',
TRUE,
'/images/coffee.jpg'),
('Powerade',
TRUE,
'/images/bluePowerade.png'),
('Dr. Pepper',
TRUE,
'/images/drPepper.jpg'),
('Orange Juice',
TRUE,
'/images/orangeJuice.jpg'),
('Bottle Water',
FALSE,
'/images/bottledWater.jpg');

INSERT INTO beverages2 (name, sizeable, imageSrc) 
VALUES 
('Milk',
FALSE,
'/images/Low-Fat-Milk-Jug.jpg'),
('Choc Milk',
FALSE, 
'/images/Chocolate-Milk-Jug.jpg'),
('Apple Juice',
FALSE, 
'/images/apple-juice.jpg'),
('Choc Shake',
TRUE, 
'/images/chocalate-shake.jpg'),
('Vanilla Shake',
TRUE, 
'/images/vanilla-shake.jpg'),
('Strwbry Shake',
TRUE, 
'/images/strawberry-shake.jpg'),
('Pink Slush',
TRUE, 
'/images/slushie-pink-lemonade.jpg'),
('Red Slush',
TRUE, 
'/images/slushie-strawberry-watermelon.jpg'),
('Blue Slush',
TRUE, 
'/images/blue-raspberry-slushie.jpg'),
('SB Smoothie',
TRUE,
'/images/SB-Smoothie.jpg'),
('MP Smoothie',
TRUE, 
'/images/mango-smoothie.jpg');

INSERT INTO mccafe (name, sizeable, imageSrc) 
VALUES 
('Crml Machi',
TRUE, 
'/images/t-mcdonalds-caramel-macchiato.jpg'),
('IC Crml Machi',
TRUE, 
'/images/t-mcdonalds-iced-caramel-macchiato.jpg'),
('Cappuccino',
TRUE, 
'/images/t-mcdonalds-cappuccino.jpg'),
('Crml Capp',
TRUE, 
'/images/t-mcdonalds-caramel-cappuccino.jpg'),
('Vani Capp',
TRUE, 
'/images/t-mcdonalds-vanilla-cappuccino.jpg'),
('Mocha',
TRUE, 
'/images/t-mcdonalds-McCafe-Mocha-Medium.jpg'),
('IC Mocha',
TRUE, 
'/images/t-mcdonalds-McCafe-Iced-Mocha-Medium.jpg'),
('Latte',
TRUE, 
'/images/t-mcdonalds-McCafe-Latte-Medium.jpg'),
('IC Latte',
TRUE, 
'/images/t-mcdonalds-iced-latte.jpg'),
('Crml Latte',
TRUE, 
'/images/t-mcdonalds-McCafe-Caramel-Latte-Medium.jpg'),
('IC Crml Latte',
TRUE, 
'/images/t-mcdonalds-iced-caramel-latte.jpg'),
('Vani Latte',
TRUE, 
'/images/t-mcdonalds-McCafe-Vanilla-Latte-Medium.jpg'),
('IC Vani Latte',
TRUE, 
'/images/t-mcdonalds-iced-french-vanilla-latte.jpg'),
('Americano',
TRUE, 
'/images/t-mcdonalds-americano.jpg'),
('IC Coffee',
TRUE, 
'/images/t-mcdonalds-Premium-Roast-Iced-Coffee-Medium.jpg'),
('IC Crml Coffee',
TRUE, 
'/images/t-mcdonalds-Caramel-Iced-Coffee.jpg'),
('IC Vani Coffee',
TRUE, 
'/images/t-mcdonalds-Vanilla-Iced-Coffee.jpg'),
('Crml Frappe',
TRUE, 
'/images/t-mcdonalds-Frappe-Caramel-Medium.jpg'),
('Mocha Frappe',
TRUE, 
'/images/t-mcdonalds-Frappe-Mocha-Medium.jpg'),
('Hot Choc',
TRUE, 
'/images/t-mcdonalds-McCafe-Hot-Chocolate-Medium.jpg');
